output:
  print-linter-name: true
  print-issued-lines: true
  formats:
    - format: text
      path: stdout

run:
  skip-dirs:
    - vendor
    - testdata
    - third_party$
    - builtin$
    - examples$

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - funlen
    - gofmt
    - goimports
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unused

linters-settings:
  funlen:
    lines: 88
  govet:
    enable:
      - shadow
  lll:
    line-length: 88
    tab-width: 4
  misspell:
    locale: UK
