version: "2"
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - funlen
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unused
  settings:
    funlen:
      lines: 88
    govet:
      enable:
        - shadow
    lll:
      line-length: 88
      tab-width: 4
    misspell:
      locale: UK
  exclusions:
    generated: lax
    paths:
      - vendor
      - testdata
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - testdata
      - third_party$
      - builtin$
      - examples$
