// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEvent = `-- name: ArchiveEvent :one
UPDATE events
SET
    status = 'CLOSED',
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, event_name, event_time, budget, status, location, description, society_id, created_by, created_at, updated_at
`

func (q *Queries) ArchiveEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, archiveEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventName,
		&i.EventTime,
		&i.Budget,
		&i.Status,
		&i.Location,
		&i.Description,
		&i.SocietyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    event_name,
    event_time,
    budget,
    location,
    description,
    society_id,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, event_name, event_time, budget, status, location, description, society_id, created_by, created_at, updated_at
`

type CreateEventParams struct {
	EventName   string
	EventTime   pgtype.Timestamptz
	Budget      pgtype.Numeric
	Location    pgtype.Text
	Description pgtype.Text
	SocietyID   pgtype.UUID
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.EventName,
		arg.EventTime,
		arg.Budget,
		arg.Location,
		arg.Description,
		arg.SocietyID,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventName,
		&i.EventTime,
		&i.Budget,
		&i.Status,
		&i.Location,
		&i.Description,
		&i.SocietyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, user_id, event_name, event_time, budget, status, location, description, society_id, created_by, created_at, updated_at FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventName,
		&i.EventTime,
		&i.Budget,
		&i.Status,
		&i.Location,
		&i.Description,
		&i.SocietyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvent = `-- name: ListEvent :many
SELECT id, user_id, event_name, event_time, budget, status, location, description, society_id, created_by, created_at, updated_at FROM events
WHERE id = $1 AND status = $2
ORDER BY event_time
`

type ListEventParams struct {
	ID     pgtype.UUID
	Status EventStatus
}

func (q *Queries) ListEvent(ctx context.Context, arg ListEventParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvent, arg.ID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventName,
			&i.EventTime,
			&i.Budget,
			&i.Status,
			&i.Location,
			&i.Description,
			&i.SocietyID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startEvent = `-- name: StartEvent :one
UPDATE events
SET 
    status = 'IN_PROGRESS',
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, event_name, event_time, budget, status, location, description, society_id, created_by, created_at, updated_at
`

func (q *Queries) StartEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, startEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventName,
		&i.EventTime,
		&i.Budget,
		&i.Status,
		&i.Location,
		&i.Description,
		&i.SocietyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
Update events
SET
    event_name = $2,
    event_time = $3,
    budget = $4,
    location = $5,
    description = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, event_name, event_time, budget, status, location, description, society_id, created_by, created_at, updated_at
`

type UpdateEventParams struct {
	ID          pgtype.UUID
	EventName   string
	EventTime   pgtype.Timestamptz
	Budget      pgtype.Numeric
	Location    pgtype.Text
	Description pgtype.Text
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.EventName,
		arg.EventTime,
		arg.Budget,
		arg.Location,
		arg.Description,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventName,
		&i.EventTime,
		&i.Budget,
		&i.Status,
		&i.Location,
		&i.Description,
		&i.SocietyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
