// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: line_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLineItem = `-- name: CreateLineItem :one
INSERT INTO line_items (
    estimated_quantity, 
    estimated_cost_per_item,
    estimated_unit_cost,
    pr_description,
    purchase_request_ID

) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, estimated_quantity, estimated_cost_per_item, estimated_unit_cost, pr_description, actual_quantity, actual_cost_per_item, actual_unit_cost, reimb_description, reimbursement_request_id, purchase_request_id, status, is_active, created_at, updated_at
`

type CreateLineItemParams struct {
	EstimatedQuantity    int64
	EstimatedCostPerItem int64
	EstimatedUnitCost    int64
	PrDescription        pgtype.Text
	PurchaseRequestID    int64
}

func (q *Queries) CreateLineItem(ctx context.Context, arg CreateLineItemParams) (LineItem, error) {
	row := q.db.QueryRow(ctx, createLineItem,
		arg.EstimatedQuantity,
		arg.EstimatedCostPerItem,
		arg.EstimatedUnitCost,
		arg.PrDescription,
		arg.PurchaseRequestID,
	)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.EstimatedQuantity,
		&i.EstimatedCostPerItem,
		&i.EstimatedUnitCost,
		&i.PrDescription,
		&i.ActualQuantity,
		&i.ActualCostPerItem,
		&i.ActualUnitCost,
		&i.ReimbDescription,
		&i.ReimbursementRequestID,
		&i.PurchaseRequestID,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLineItem = `-- name: DeleteLineItem :exec
DELETE FROM line_items
WHERE id = $1
`

func (q *Queries) DeleteLineItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLineItem, id)
	return err
}

const getLineItemByID = `-- name: GetLineItemByID :one
SELECT id, estimated_quantity, estimated_cost_per_item, estimated_unit_cost, pr_description, actual_quantity, actual_cost_per_item, actual_unit_cost, reimb_description, reimbursement_request_id, purchase_request_id, status, is_active, created_at, updated_at FROM line_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLineItemByID(ctx context.Context, id int64) (LineItem, error) {
	row := q.db.QueryRow(ctx, getLineItemByID, id)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.EstimatedQuantity,
		&i.EstimatedCostPerItem,
		&i.EstimatedUnitCost,
		&i.PrDescription,
		&i.ActualQuantity,
		&i.ActualCostPerItem,
		&i.ActualUnitCost,
		&i.ReimbDescription,
		&i.ReimbursementRequestID,
		&i.PurchaseRequestID,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLineItemByPRID = `-- name: GetLineItemByPRID :one
SELECT id, estimated_quantity, estimated_cost_per_item, estimated_unit_cost, pr_description, actual_quantity, actual_cost_per_item, actual_unit_cost, reimb_description, reimbursement_request_id, purchase_request_id, status, is_active, created_at, updated_at FROM line_items
WHERE purchase_request_ID = $1 LIMIT 1
`

func (q *Queries) GetLineItemByPRID(ctx context.Context, purchaseRequestID int64) (LineItem, error) {
	row := q.db.QueryRow(ctx, getLineItemByPRID, purchaseRequestID)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.EstimatedQuantity,
		&i.EstimatedCostPerItem,
		&i.EstimatedUnitCost,
		&i.PrDescription,
		&i.ActualQuantity,
		&i.ActualCostPerItem,
		&i.ActualUnitCost,
		&i.ReimbDescription,
		&i.ReimbursementRequestID,
		&i.PurchaseRequestID,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLineItemByReimbID = `-- name: GetLineItemByReimbID :one
SELECT id, estimated_quantity, estimated_cost_per_item, estimated_unit_cost, pr_description, actual_quantity, actual_cost_per_item, actual_unit_cost, reimb_description, reimbursement_request_id, purchase_request_id, status, is_active, created_at, updated_at FROM line_items
WHERE reimbursement_request_ID = $1 LIMIT 1
`

func (q *Queries) GetLineItemByReimbID(ctx context.Context, reimbursementRequestID pgtype.Int8) (LineItem, error) {
	row := q.db.QueryRow(ctx, getLineItemByReimbID, reimbursementRequestID)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.EstimatedQuantity,
		&i.EstimatedCostPerItem,
		&i.EstimatedUnitCost,
		&i.PrDescription,
		&i.ActualQuantity,
		&i.ActualCostPerItem,
		&i.ActualUnitCost,
		&i.ReimbDescription,
		&i.ReimbursementRequestID,
		&i.PurchaseRequestID,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLineItems = `-- name: ListLineItems :many
SELECT id, estimated_quantity, estimated_cost_per_item, estimated_unit_cost, pr_description, actual_quantity, actual_cost_per_item, actual_unit_cost, reimb_description, reimbursement_request_id, purchase_request_id, status, is_active, created_at, updated_at FROM line_items
ORDER BY id
LIMIT $1
`

func (q *Queries) ListLineItems(ctx context.Context, limit int32) ([]LineItem, error) {
	rows, err := q.db.Query(ctx, listLineItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LineItem
	for rows.Next() {
		var i LineItem
		if err := rows.Scan(
			&i.ID,
			&i.EstimatedQuantity,
			&i.EstimatedCostPerItem,
			&i.EstimatedUnitCost,
			&i.PrDescription,
			&i.ActualQuantity,
			&i.ActualCostPerItem,
			&i.ActualUnitCost,
			&i.ReimbDescription,
			&i.ReimbursementRequestID,
			&i.PurchaseRequestID,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLineItem = `-- name: UpdateLineItem :one
UPDATE line_items
SET 
    estimated_quantity = $2, 
    estimated_cost_per_item = $3, 
    estimated_unit_cost = $4, 
    pr_description = $5, 

    actual_quantity = $6,
    actual_cost_per_item = $7,
	actual_unit_cost = $8,
	reimb_description = $9,

    reimbursement_request_ID = $10,

    status = $11,
    is_active = $12,
    
    updated_at = NOW()
WHERE id = $1
RETURNING id, estimated_quantity, estimated_cost_per_item, estimated_unit_cost, pr_description, actual_quantity, actual_cost_per_item, actual_unit_cost, reimb_description, reimbursement_request_id, purchase_request_id, status, is_active, created_at, updated_at
`

type UpdateLineItemParams struct {
	ID                     int64
	EstimatedQuantity      int64
	EstimatedCostPerItem   int64
	EstimatedUnitCost      int64
	PrDescription          pgtype.Text
	ActualQuantity         pgtype.Int8
	ActualCostPerItem      pgtype.Int8
	ActualUnitCost         pgtype.Int8
	ReimbDescription       pgtype.Text
	ReimbursementRequestID pgtype.Int8
	Status                 NullLineItemStatus
	IsActive               pgtype.Bool
}

func (q *Queries) UpdateLineItem(ctx context.Context, arg UpdateLineItemParams) (LineItem, error) {
	row := q.db.QueryRow(ctx, updateLineItem,
		arg.ID,
		arg.EstimatedQuantity,
		arg.EstimatedCostPerItem,
		arg.EstimatedUnitCost,
		arg.PrDescription,
		arg.ActualQuantity,
		arg.ActualCostPerItem,
		arg.ActualUnitCost,
		arg.ReimbDescription,
		arg.ReimbursementRequestID,
		arg.Status,
		arg.IsActive,
	)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.EstimatedQuantity,
		&i.EstimatedCostPerItem,
		&i.EstimatedUnitCost,
		&i.PrDescription,
		&i.ActualQuantity,
		&i.ActualCostPerItem,
		&i.ActualUnitCost,
		&i.ReimbDescription,
		&i.ReimbursementRequestID,
		&i.PurchaseRequestID,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
