// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventStatus string

const (
	EventStatusDRAFT      EventStatus = "DRAFT"
	EventStatusINPROGRESS EventStatus = "IN_PROGRESS"
	EventStatusCLOSED     EventStatus = "CLOSED"
)

func (e *EventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventStatus(s)
	case string:
		*e = EventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EventStatus: %T", src)
	}
	return nil
}

type NullEventStatus struct {
	EventStatus EventStatus
	Valid       bool // Valid is true if EventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventStatus), nil
}

type PurchaseRequestStatus string

const (
	PurchaseRequestStatusDraft    PurchaseRequestStatus = "draft"
	PurchaseRequestStatusPending  PurchaseRequestStatus = "pending"
	PurchaseRequestStatusApproved PurchaseRequestStatus = "approved"
	PurchaseRequestStatusRejected PurchaseRequestStatus = "rejected"
)

func (e *PurchaseRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PurchaseRequestStatus(s)
	case string:
		*e = PurchaseRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PurchaseRequestStatus: %T", src)
	}
	return nil
}

type NullPurchaseRequestStatus struct {
	PurchaseRequestStatus PurchaseRequestStatus
	Valid                 bool // Valid is true if PurchaseRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPurchaseRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PurchaseRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PurchaseRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPurchaseRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PurchaseRequestStatus), nil
}

type Event struct {
	ID          pgtype.UUID
	UserID      pgtype.Int8
	EventName   string
	EventTime   pgtype.Timestamptz
	Budget      int64
	Status      EventStatus
	Location    pgtype.Text
	Description pgtype.Text
	SocietyID   pgtype.UUID
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PurchaseRequest struct {
	ID              int64
	CreatedByUserID int64
	EventID         pgtype.Int8
	PortfolioID     pgtype.Int8
	Title           string
	Description     pgtype.Text
	ExpectedBudget  pgtype.Int8
	ActualBudget    pgtype.Int8
	Status          PurchaseRequestStatus
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type User struct {
	ID        int64
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
