// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchase_request.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPR = `-- name: CreatePR :one
INSERT INTO purchase_requests (
    created_by_user_id, event_id, portfolio_id, title, description, expected_budget, actual_budget
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, created_by_user_id, event_id, portfolio_id, title, description, expected_budget, actual_budget, status, created_at, updated_at
`

type CreatePRParams struct {
	CreatedByUserID int64
	EventID         pgtype.Int8
	PortfolioID     pgtype.Int8
	Title           string
	Description     pgtype.Text
	ExpectedBudget  pgtype.Int8
	ActualBudget    pgtype.Int8
}

func (q *Queries) CreatePR(ctx context.Context, arg CreatePRParams) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, createPR,
		arg.CreatedByUserID,
		arg.EventID,
		arg.PortfolioID,
		arg.Title,
		arg.Description,
		arg.ExpectedBudget,
		arg.ActualBudget,
	)
	var i PurchaseRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.EventID,
		&i.PortfolioID,
		&i.Title,
		&i.Description,
		&i.ExpectedBudget,
		&i.ActualBudget,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePR = `-- name: DeletePR :exec
DELETE FROM purchase_requests
WHERE id = $1
`

func (q *Queries) DeletePR(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePR, id)
	return err
}

const listPR = `-- name: ListPR :many
SELECT id, created_by_user_id, event_id, portfolio_id, title, description, expected_budget, actual_budget, status, created_at, updated_at FROM purchase_requests
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListPRParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPR(ctx context.Context, arg ListPRParams) ([]PurchaseRequest, error) {
	rows, err := q.db.Query(ctx, listPR, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseRequest
	for rows.Next() {
		var i PurchaseRequest
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUserID,
			&i.EventID,
			&i.PortfolioID,
			&i.Title,
			&i.Description,
			&i.ExpectedBudget,
			&i.ActualBudget,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePR = `-- name: UpdatePR :one
UPDATE purchase_requests
SET expected_budget = $2,
    actual_budget = $3
WHERE id = $1
RETURNING id, created_by_user_id, event_id, portfolio_id, title, description, expected_budget, actual_budget, status, created_at, updated_at
`

type UpdatePRParams struct {
	ID             int64
	ExpectedBudget pgtype.Int8
	ActualBudget   pgtype.Int8
}

func (q *Queries) UpdatePR(ctx context.Context, arg UpdatePRParams) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, updatePR, arg.ID, arg.ExpectedBudget, arg.ActualBudget)
	var i PurchaseRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.EventID,
		&i.PortfolioID,
		&i.Title,
		&i.Description,
		&i.ExpectedBudget,
		&i.ActualBudget,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPR = `-- name: getPR :one
SELECT id, created_by_user_id, event_id, portfolio_id, title, description, expected_budget, actual_budget, status, created_at, updated_at FROM purchase_requests
WHERE id = $1 LIMIT 1
`

func (q *Queries) getPR(ctx context.Context, id int64) (PurchaseRequest, error) {
	row := q.db.QueryRow(ctx, getPR, id)
	var i PurchaseRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.EventID,
		&i.PortfolioID,
		&i.Title,
		&i.Description,
		&i.ExpectedBudget,
		&i.ActualBudget,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
