services:
  warchest-dev-container:
    container_name: warchest-dev-container
    image: ghcr.io/devsoc-unsw/warchest-devcontainer
    stdin_open: true
    tty: true
    ports:
      # expose ports (3000 computer <-> 3000 on the container)
      - "3000:3000"
    volumes:
      - ../:/root/warchest
    environment:
      - NODE_ENV=development
      - BE_DATABASE_URL=postgres://postgres:password@warchest-postgres-be:5432/warchest
      - MM_DATABASE_URL=postgres://postgres:password@warchest-postgres-mm:5432/money_module
      - TIGERBEETLE_ADDRESS=tigerbeetle:3000
      - SPICEDB_ADDRESS=warchest-spicedb:50051
      - SPICEDB_PRESHARED_KEY=warchestdabest
    networks:
      - devsoc-network
    depends_on:
      warchest-postgres-be:
        condition: service_healthy
      warchest-postgres-mm:
        condition: service_healthy
      warchest-tigerbeetle:
        condition: service_started
      warchest-spicedb:
        condition: service_started
    security_opt:
      - seccomp:unconfined

  warchest-postgres-be:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warchest
    networks:
      - devsoc-network
    volumes:
      - postgres_be_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  warchest-postgres-mm:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: money_module
    networks:
      - devsoc-network
    volumes:
      - postgres_mm_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  warchest-tigerbeetle:
    build:
      context: ./tigerbeetle
      dockerfile: Dockerfile
    networks:
      - devsoc-network
    volumes:
      - tigerbeetle_data:/data
    security_opt:
      - seccomp:unconfined

  warchest-spicedb:
    image: authzed/spicedb
    command: serve --grpc-preshared-key "warchestdabest"
    ports:
      - "50051:50051"
    networks:
      - devsoc-network

volumes:
  postgres_be_data:
  postgres_mm_data:
  tigerbeetle_data:

networks:
  devsoc-network:
    driver: bridge
