services:
  warchest-dev-container:
    container_name: warchest-dev-container
    image: ghcr.io/devsoc-unsw/warchest-devcontainer
    stdin_open: true
    tty: true
    ports:
      # expose ports (3000 computer <-> 3000 on the container)
      - "3000:3000"
    volumes:
      - ../:/root/warchest
    environment:
      - NODE_ENV=development
      - BE_DATABASE_URL=postgres://postgres:password@warchest-postgres-be:5432/warchest
      - MM_DATABASE_URL=postgres://postgres:password@warchest-postgres-mm:5432/money_module
      - TIGERBEETLE_ADDRESS=tigerbeetle:3000
    networks:
      - devsoc-network
    depends_on:
      warchest-postgres-be:
        condition: service_healthy
      warchest-postgres-mm:
        condition: service_healthy
      warchest-tigerbeetle:
        condition: service_started
    security_opt:
      - seccomp:unconfined

  warchest-postgres-be:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warchest
    networks:
      - devsoc-network
    volumes:
      - postgres_be_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  warchest-postgres-mm:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: money_module
    networks:
      - devsoc-network
    volumes:
      - postgres_mm_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  warchest-tigerbeetle:
    build:
      context: ./tigerbeetle
      dockerfile: Dockerfile
    networks:
      - devsoc-network
    volumes:
      - tigerbeetle_data:/data
    security_opt:
      - seccomp:unconfined
  mock-spicedb:
    container_name: "spicedb"
    build: "."
    command: "serve"
    restart: "no"
    ports:
      - "50051:50051"
    environment:
      - "SPICEDB_LOG_FORMAT=json"
      - "SPICEDB_LOG_LEVEL=info"
      - "SPICEDB_GRPC_PRESHARED_KEY=super-secret-key"
      - "SPICEDB_DATASTORE_ENGINE=memory"
      - "SPICEDB_OTEL_PROVIDER=otlpgrpc"
      - "SPICEDB_OTEL_SAMPLE_RATIO=1"
      - "SPICEDB_TELEMETRY_ENDPOINT="
      - "SPICEDB_GRPC_LOG_REQUESTS_ENABLED=false"
      - "SPICEDB_GRPC_LOG_RESPONSES_ENABLED=false"
      - "SPICEDB_STREAMING_API_RESPONSE_DELAY_TIMEOUT=0s"
      - "SPICEDB_ENABLE_PERFORMANCE_INSIGHT_METRICS=true"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:50051"]
      interval: "5s"
      timeout: "30s"
      retries: 3
 
volumes:
  postgres_be_data:
  postgres_mm_data:
  tigerbeetle_data:

networks:
  devsoc-network:
    driver: bridge
