// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mm.proto

package money_module_protobuff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_FAILED  Status = 0
	Status_PENDING Status = 1
	Status_PASSED  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "FAILED",
		1: "PENDING",
		2: "PASSED",
	}
	Status_value = map[string]int32{
		"FAILED":  0,
		"PENDING": 1,
		"PASSED":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_mm_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_mm_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{0}
}

type OwnerType int32

const (
	OwnerType_USER OwnerType = 0
	OwnerType_ORG  OwnerType = 1
)

// Enum value maps for OwnerType.
var (
	OwnerType_name = map[int32]string{
		0: "USER",
		1: "ORG",
	}
	OwnerType_value = map[string]int32{
		"USER": 0,
		"ORG":  1,
	}
)

func (x OwnerType) Enum() *OwnerType {
	p := new(OwnerType)
	*p = x
	return p
}

func (x OwnerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OwnerType) Descriptor() protoreflect.EnumDescriptor {
	return file_mm_proto_enumTypes[1].Descriptor()
}

func (OwnerType) Type() protoreflect.EnumType {
	return &file_mm_proto_enumTypes[1]
}

func (x OwnerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OwnerType.Descriptor instead.
func (OwnerType) EnumDescriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{1}
}

type WalletType int32

const (
	WalletType_ACCOUNT WalletType = 0
	WalletType_BUDGET  WalletType = 1
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "ACCOUNT",
		1: "BUDGET",
	}
	WalletType_value = map[string]int32{
		"ACCOUNT": 0,
		"BUDGET":  1,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_mm_proto_enumTypes[2].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_mm_proto_enumTypes[2]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{2}
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_mm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayerId       *UUID                  `protobuf:"bytes,1,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	PayeeId       *UUID                  `protobuf:"bytes,2,opt,name=payee_id,json=payeeId,proto3" json:"payee_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_mm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentRequest) GetPayerId() *UUID {
	if x != nil {
		return x.PayerId
	}
	return nil
}

func (x *PaymentRequest) GetPayeeId() *UUID {
	if x != nil {
		return x.PayeeId
	}
	return nil
}

func (x *PaymentRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RootPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NonRootId     *UUID                  `protobuf:"bytes,1,opt,name=non_root_id,json=nonRootId,proto3" json:"non_root_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootPaymentRequest) Reset() {
	*x = RootPaymentRequest{}
	mi := &file_mm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootPaymentRequest) ProtoMessage() {}

func (x *RootPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootPaymentRequest.ProtoReflect.Descriptor instead.
func (*RootPaymentRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{2}
}

func (x *RootPaymentRequest) GetNonRootId() *UUID {
	if x != nil {
		return x.NonRootId
	}
	return nil
}

func (x *RootPaymentRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId *UUID                  `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=money_module.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_mm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentResponse) GetTransactionId() *UUID {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *PaymentResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_FAILED
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayerId       *UUID                  `protobuf:"bytes,1,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	PayeeId       *UUID                  `protobuf:"bytes,2,opt,name=payee_id,json=payeeId,proto3" json:"payee_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_mm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{4}
}

func (x *SendRequest) GetPayerId() *UUID {
	if x != nil {
		return x.PayerId
	}
	return nil
}

func (x *SendRequest) GetPayeeId() *UUID {
	if x != nil {
		return x.PayeeId
	}
	return nil
}

func (x *SendRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId *UUID                  `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=money_module.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_mm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{5}
}

func (x *SendResponse) GetTransactionId() *UUID {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *SendResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_FAILED
}

type TransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransfersRequest) Reset() {
	*x = TransfersRequest{}
	mi := &file_mm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransfersRequest) ProtoMessage() {}

func (x *TransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransfersRequest.ProtoReflect.Descriptor instead.
func (*TransfersRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{6}
}

func (x *TransfersRequest) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    *UUID                  `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Sender        *UUID                  `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      *UUID                  `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_mm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{7}
}

func (x *Transfer) GetTransferId() *UUID {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *Transfer) GetSender() *UUID {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Transfer) GetReceiver() *UUID {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Transfer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransfersResponse) Reset() {
	*x = TransfersResponse{}
	mi := &file_mm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransfersResponse) ProtoMessage() {}

func (x *TransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransfersResponse.ProtoReflect.Descriptor instead.
func (*TransfersResponse) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{8}
}

func (x *TransfersResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type WalletDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerType     OwnerType              `protobuf:"varint,2,opt,name=owner_type,json=ownerType,proto3,enum=money_module.OwnerType" json:"owner_type,omitempty"`
	OwnerId       *UUID                  `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WalletType    WalletType             `protobuf:"varint,4,opt,name=wallet_type,json=walletType,proto3,enum=money_module.WalletType" json:"wallet_type,omitempty"`
	WalletName    string                 `protobuf:"bytes,5,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	IsArchived    bool                   `protobuf:"varint,6,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletDetailsResponse) Reset() {
	*x = WalletDetailsResponse{}
	mi := &file_mm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletDetailsResponse) ProtoMessage() {}

func (x *WalletDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletDetailsResponse.ProtoReflect.Descriptor instead.
func (*WalletDetailsResponse) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{9}
}

func (x *WalletDetailsResponse) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *WalletDetailsResponse) GetOwnerType() OwnerType {
	if x != nil {
		return x.OwnerType
	}
	return OwnerType_USER
}

func (x *WalletDetailsResponse) GetOwnerId() *UUID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *WalletDetailsResponse) GetWalletType() WalletType {
	if x != nil {
		return x.WalletType
	}
	return WalletType_ACCOUNT
}

func (x *WalletDetailsResponse) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *WalletDetailsResponse) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

type GetWalletDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletDetailsRequest) Reset() {
	*x = GetWalletDetailsRequest{}
	mi := &file_mm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletDetailsRequest) ProtoMessage() {}

func (x *GetWalletDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetWalletDetailsRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{10}
}

func (x *GetWalletDetailsRequest) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

type ArchiveWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveWalletRequest) Reset() {
	*x = ArchiveWalletRequest{}
	mi := &file_mm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveWalletRequest) ProtoMessage() {}

func (x *ArchiveWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveWalletRequest.ProtoReflect.Descriptor instead.
func (*ArchiveWalletRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{11}
}

func (x *ArchiveWalletRequest) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     OwnerType              `protobuf:"varint,1,opt,name=owner_type,json=ownerType,proto3,enum=money_module.OwnerType" json:"owner_type,omitempty"`
	OwnerId       *UUID                  `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	BudgetName    string                 `protobuf:"bytes,3,opt,name=budget_name,json=budgetName,proto3" json:"budget_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_mm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{12}
}

func (x *CreateAccountRequest) GetOwnerType() OwnerType {
	if x != nil {
		return x.OwnerType
	}
	return OwnerType_USER
}

func (x *CreateAccountRequest) GetOwnerId() *UUID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *CreateAccountRequest) GetBudgetName() string {
	if x != nil {
		return x.BudgetName
	}
	return ""
}

type CreateBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     OwnerType              `protobuf:"varint,1,opt,name=owner_type,json=ownerType,proto3,enum=money_module.OwnerType" json:"owner_type,omitempty"`
	OwnerId       *UUID                  `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	BudgetName    string                 `protobuf:"bytes,3,opt,name=budget_name,json=budgetName,proto3" json:"budget_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetRequest) Reset() {
	*x = CreateBudgetRequest{}
	mi := &file_mm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetRequest) ProtoMessage() {}

func (x *CreateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetRequest.ProtoReflect.Descriptor instead.
func (*CreateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{13}
}

func (x *CreateBudgetRequest) GetOwnerType() OwnerType {
	if x != nil {
		return x.OwnerType
	}
	return OwnerType_USER
}

func (x *CreateBudgetRequest) GetOwnerId() *UUID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *CreateBudgetRequest) GetBudgetName() string {
	if x != nil {
		return x.BudgetName
	}
	return ""
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerType     OwnerType              `protobuf:"varint,2,opt,name=owner_type,json=ownerType,proto3,enum=money_module.OwnerType" json:"owner_type,omitempty"`
	OwnerId       *UUID                  `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WalletName    string                 `protobuf:"bytes,4,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_mm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAccountRequest) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateAccountRequest) GetOwnerType() OwnerType {
	if x != nil {
		return x.OwnerType
	}
	return OwnerType_USER
}

func (x *UpdateAccountRequest) GetOwnerId() *UUID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *UpdateAccountRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

type UpdateBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerType     OwnerType              `protobuf:"varint,2,opt,name=owner_type,json=ownerType,proto3,enum=money_module.OwnerType" json:"owner_type,omitempty"`
	OwnerId       *UUID                  `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WalletName    string                 `protobuf:"bytes,4,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBudgetRequest) Reset() {
	*x = UpdateBudgetRequest{}
	mi := &file_mm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBudgetRequest) ProtoMessage() {}

func (x *UpdateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBudgetRequest.ProtoReflect.Descriptor instead.
func (*UpdateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_mm_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBudgetRequest) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateBudgetRequest) GetOwnerType() OwnerType {
	if x != nil {
		return x.OwnerType
	}
	return OwnerType_USER
}

func (x *UpdateBudgetRequest) GetOwnerId() *UUID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *UpdateBudgetRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

var File_mm_proto protoreflect.FileDescriptor

const file_mm_proto_rawDesc = "" +
	"\n" +
	"\bmm.proto\x12\fmoney_module\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\x86\x01\n" +
	"\x0ePaymentRequest\x12-\n" +
	"\bpayer_id\x18\x01 \x01(\v2\x12.money_module.UUIDR\apayerId\x12-\n" +
	"\bpayee_id\x18\x02 \x01(\v2\x12.money_module.UUIDR\apayeeId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"`\n" +
	"\x12RootPaymentRequest\x122\n" +
	"\vnon_root_id\x18\x01 \x01(\v2\x12.money_module.UUIDR\tnonRootId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"z\n" +
	"\x0fPaymentResponse\x129\n" +
	"\x0etransaction_id\x18\x01 \x01(\v2\x12.money_module.UUIDR\rtransactionId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.money_module.StatusR\x06status\"\x83\x01\n" +
	"\vSendRequest\x12-\n" +
	"\bpayer_id\x18\x01 \x01(\v2\x12.money_module.UUIDR\apayerId\x12-\n" +
	"\bpayee_id\x18\x02 \x01(\v2\x12.money_module.UUIDR\apayeeId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"w\n" +
	"\fSendResponse\x129\n" +
	"\x0etransaction_id\x18\x01 \x01(\v2\x12.money_module.UUIDR\rtransactionId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.money_module.StatusR\x06status\"6\n" +
	"\x10TransfersRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.money_module.UUIDR\x02id\"\xbd\x01\n" +
	"\bTransfer\x123\n" +
	"\vtransfer_id\x18\x01 \x01(\v2\x12.money_module.UUIDR\n" +
	"transferId\x12*\n" +
	"\x06sender\x18\x02 \x01(\v2\x12.money_module.UUIDR\x06sender\x12.\n" +
	"\breceiver\x18\x03 \x01(\v2\x12.money_module.UUIDR\breceiver\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"I\n" +
	"\x11TransfersResponse\x124\n" +
	"\ttransfers\x18\x01 \x03(\v2\x16.money_module.TransferR\ttransfers\"\x9f\x02\n" +
	"\x15WalletDetailsResponse\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.money_module.UUIDR\x02id\x126\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\x0e2\x17.money_module.OwnerTypeR\townerType\x12-\n" +
	"\bowner_id\x18\x03 \x01(\v2\x12.money_module.UUIDR\aownerId\x129\n" +
	"\vwallet_type\x18\x04 \x01(\x0e2\x18.money_module.WalletTypeR\n" +
	"walletType\x12\x1f\n" +
	"\vwallet_name\x18\x05 \x01(\tR\n" +
	"walletName\x12\x1f\n" +
	"\vis_archived\x18\x06 \x01(\bR\n" +
	"isArchived\"=\n" +
	"\x17GetWalletDetailsRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.money_module.UUIDR\x02id\":\n" +
	"\x14ArchiveWalletRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.money_module.UUIDR\x02id\"\x9e\x01\n" +
	"\x14CreateAccountRequest\x126\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\x0e2\x17.money_module.OwnerTypeR\townerType\x12-\n" +
	"\bowner_id\x18\x02 \x01(\v2\x12.money_module.UUIDR\aownerId\x12\x1f\n" +
	"\vbudget_name\x18\x03 \x01(\tR\n" +
	"budgetName\"\x9d\x01\n" +
	"\x13CreateBudgetRequest\x126\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\x0e2\x17.money_module.OwnerTypeR\townerType\x12-\n" +
	"\bowner_id\x18\x02 \x01(\v2\x12.money_module.UUIDR\aownerId\x12\x1f\n" +
	"\vbudget_name\x18\x03 \x01(\tR\n" +
	"budgetName\"\xc2\x01\n" +
	"\x14UpdateAccountRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.money_module.UUIDR\x02id\x126\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\x0e2\x17.money_module.OwnerTypeR\townerType\x12-\n" +
	"\bowner_id\x18\x03 \x01(\v2\x12.money_module.UUIDR\aownerId\x12\x1f\n" +
	"\vwallet_name\x18\x04 \x01(\tR\n" +
	"walletName\"\xc1\x01\n" +
	"\x13UpdateBudgetRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.money_module.UUIDR\x02id\x126\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\x0e2\x17.money_module.OwnerTypeR\townerType\x12-\n" +
	"\bowner_id\x18\x03 \x01(\v2\x12.money_module.UUIDR\aownerId\x12\x1f\n" +
	"\vwallet_name\x18\x04 \x01(\tR\n" +
	"walletName*-\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06FAILED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06PASSED\x10\x02*\x1e\n" +
	"\tOwnerType\x12\b\n" +
	"\x04USER\x10\x00\x12\a\n" +
	"\x03ORG\x10\x01*%\n" +
	"\n" +
	"WalletType\x12\v\n" +
	"\aACCOUNT\x10\x00\x12\n" +
	"\n" +
	"\x06BUDGET\x10\x012\xff\n" +
	"\n" +
	"\vMoneyModule\x12X\n" +
	"\rCreateAccount\x12\".money_module.CreateAccountRequest\x1a#.money_module.WalletDetailsResponse\x12Y\n" +
	"\vReadAccount\x12%.money_module.GetWalletDetailsRequest\x1a#.money_module.WalletDetailsResponse\x12X\n" +
	"\rUpdateAccount\x12\".money_module.UpdateAccountRequest\x1a#.money_module.WalletDetailsResponse\x12Y\n" +
	"\x0eArchiveAccount\x12\".money_module.ArchiveWalletRequest\x1a#.money_module.WalletDetailsResponse\x12V\n" +
	"\fCreateBudget\x12!.money_module.CreateBudgetRequest\x1a#.money_module.WalletDetailsResponse\x12X\n" +
	"\n" +
	"ReadBudget\x12%.money_module.GetWalletDetailsRequest\x1a#.money_module.WalletDetailsResponse\x12V\n" +
	"\fUpdateBudget\x12!.money_module.UpdateBudgetRequest\x1a#.money_module.WalletDetailsResponse\x12X\n" +
	"\rArchiveBudget\x12\".money_module.ArchiveWalletRequest\x1a#.money_module.WalletDetailsResponse\x12S\n" +
	"\x14PayAccountFromBudget\x12\x1c.money_module.PaymentRequest\x1a\x1d.money_module.PaymentResponse\x12S\n" +
	"\x14PayBudgetFromAccount\x12\x1c.money_module.PaymentRequest\x1a\x1d.money_module.PaymentResponse\x12U\n" +
	"\x12PayRootFromAccount\x12 .money_module.RootPaymentRequest\x1a\x1d.money_module.PaymentResponse\x12U\n" +
	"\x12PayAccountFromRoot\x12 .money_module.RootPaymentRequest\x1a\x1d.money_module.PaymentResponse\x12K\n" +
	"\x12SendBetweenBudgets\x12\x19.money_module.SendRequest\x1a\x1a.money_module.SendResponse\x12V\n" +
	"\x13GetAccountTransfers\x12\x1e.money_module.TransfersRequest\x1a\x1f.money_module.TransfersResponse\x12U\n" +
	"\x12GetBudgetTransfers\x12\x1e.money_module.TransfersRequest\x1a\x1f.money_module.TransfersResponse\x12N\n" +
	"\x13GetSocietyTransfers\x12\x16.google.protobuf.Empty\x1a\x1f.money_module.TransfersResponseB\x1aZ\x18./money_module_protobuffb\x06proto3"

var (
	file_mm_proto_rawDescOnce sync.Once
	file_mm_proto_rawDescData []byte
)

func file_mm_proto_rawDescGZIP() []byte {
	file_mm_proto_rawDescOnce.Do(func() {
		file_mm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mm_proto_rawDesc), len(file_mm_proto_rawDesc)))
	})
	return file_mm_proto_rawDescData
}

var file_mm_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mm_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_mm_proto_goTypes = []any{
	(Status)(0),                     // 0: money_module.Status
	(OwnerType)(0),                  // 1: money_module.OwnerType
	(WalletType)(0),                 // 2: money_module.WalletType
	(*UUID)(nil),                    // 3: money_module.UUID
	(*PaymentRequest)(nil),          // 4: money_module.PaymentRequest
	(*RootPaymentRequest)(nil),      // 5: money_module.RootPaymentRequest
	(*PaymentResponse)(nil),         // 6: money_module.PaymentResponse
	(*SendRequest)(nil),             // 7: money_module.SendRequest
	(*SendResponse)(nil),            // 8: money_module.SendResponse
	(*TransfersRequest)(nil),        // 9: money_module.TransfersRequest
	(*Transfer)(nil),                // 10: money_module.Transfer
	(*TransfersResponse)(nil),       // 11: money_module.TransfersResponse
	(*WalletDetailsResponse)(nil),   // 12: money_module.WalletDetailsResponse
	(*GetWalletDetailsRequest)(nil), // 13: money_module.GetWalletDetailsRequest
	(*ArchiveWalletRequest)(nil),    // 14: money_module.ArchiveWalletRequest
	(*CreateAccountRequest)(nil),    // 15: money_module.CreateAccountRequest
	(*CreateBudgetRequest)(nil),     // 16: money_module.CreateBudgetRequest
	(*UpdateAccountRequest)(nil),    // 17: money_module.UpdateAccountRequest
	(*UpdateBudgetRequest)(nil),     // 18: money_module.UpdateBudgetRequest
	(*emptypb.Empty)(nil),           // 19: google.protobuf.Empty
}
var file_mm_proto_depIdxs = []int32{
	3,  // 0: money_module.PaymentRequest.payer_id:type_name -> money_module.UUID
	3,  // 1: money_module.PaymentRequest.payee_id:type_name -> money_module.UUID
	3,  // 2: money_module.RootPaymentRequest.non_root_id:type_name -> money_module.UUID
	3,  // 3: money_module.PaymentResponse.transaction_id:type_name -> money_module.UUID
	0,  // 4: money_module.PaymentResponse.status:type_name -> money_module.Status
	3,  // 5: money_module.SendRequest.payer_id:type_name -> money_module.UUID
	3,  // 6: money_module.SendRequest.payee_id:type_name -> money_module.UUID
	3,  // 7: money_module.SendResponse.transaction_id:type_name -> money_module.UUID
	0,  // 8: money_module.SendResponse.status:type_name -> money_module.Status
	3,  // 9: money_module.TransfersRequest.id:type_name -> money_module.UUID
	3,  // 10: money_module.Transfer.transfer_id:type_name -> money_module.UUID
	3,  // 11: money_module.Transfer.sender:type_name -> money_module.UUID
	3,  // 12: money_module.Transfer.receiver:type_name -> money_module.UUID
	10, // 13: money_module.TransfersResponse.transfers:type_name -> money_module.Transfer
	3,  // 14: money_module.WalletDetailsResponse.id:type_name -> money_module.UUID
	1,  // 15: money_module.WalletDetailsResponse.owner_type:type_name -> money_module.OwnerType
	3,  // 16: money_module.WalletDetailsResponse.owner_id:type_name -> money_module.UUID
	2,  // 17: money_module.WalletDetailsResponse.wallet_type:type_name -> money_module.WalletType
	3,  // 18: money_module.GetWalletDetailsRequest.id:type_name -> money_module.UUID
	3,  // 19: money_module.ArchiveWalletRequest.id:type_name -> money_module.UUID
	1,  // 20: money_module.CreateAccountRequest.owner_type:type_name -> money_module.OwnerType
	3,  // 21: money_module.CreateAccountRequest.owner_id:type_name -> money_module.UUID
	1,  // 22: money_module.CreateBudgetRequest.owner_type:type_name -> money_module.OwnerType
	3,  // 23: money_module.CreateBudgetRequest.owner_id:type_name -> money_module.UUID
	3,  // 24: money_module.UpdateAccountRequest.id:type_name -> money_module.UUID
	1,  // 25: money_module.UpdateAccountRequest.owner_type:type_name -> money_module.OwnerType
	3,  // 26: money_module.UpdateAccountRequest.owner_id:type_name -> money_module.UUID
	3,  // 27: money_module.UpdateBudgetRequest.id:type_name -> money_module.UUID
	1,  // 28: money_module.UpdateBudgetRequest.owner_type:type_name -> money_module.OwnerType
	3,  // 29: money_module.UpdateBudgetRequest.owner_id:type_name -> money_module.UUID
	15, // 30: money_module.MoneyModule.CreateAccount:input_type -> money_module.CreateAccountRequest
	13, // 31: money_module.MoneyModule.ReadAccount:input_type -> money_module.GetWalletDetailsRequest
	17, // 32: money_module.MoneyModule.UpdateAccount:input_type -> money_module.UpdateAccountRequest
	14, // 33: money_module.MoneyModule.ArchiveAccount:input_type -> money_module.ArchiveWalletRequest
	16, // 34: money_module.MoneyModule.CreateBudget:input_type -> money_module.CreateBudgetRequest
	13, // 35: money_module.MoneyModule.ReadBudget:input_type -> money_module.GetWalletDetailsRequest
	18, // 36: money_module.MoneyModule.UpdateBudget:input_type -> money_module.UpdateBudgetRequest
	14, // 37: money_module.MoneyModule.ArchiveBudget:input_type -> money_module.ArchiveWalletRequest
	4,  // 38: money_module.MoneyModule.PayAccountFromBudget:input_type -> money_module.PaymentRequest
	4,  // 39: money_module.MoneyModule.PayBudgetFromAccount:input_type -> money_module.PaymentRequest
	5,  // 40: money_module.MoneyModule.PayRootFromAccount:input_type -> money_module.RootPaymentRequest
	5,  // 41: money_module.MoneyModule.PayAccountFromRoot:input_type -> money_module.RootPaymentRequest
	7,  // 42: money_module.MoneyModule.SendBetweenBudgets:input_type -> money_module.SendRequest
	9,  // 43: money_module.MoneyModule.GetAccountTransfers:input_type -> money_module.TransfersRequest
	9,  // 44: money_module.MoneyModule.GetBudgetTransfers:input_type -> money_module.TransfersRequest
	19, // 45: money_module.MoneyModule.GetSocietyTransfers:input_type -> google.protobuf.Empty
	12, // 46: money_module.MoneyModule.CreateAccount:output_type -> money_module.WalletDetailsResponse
	12, // 47: money_module.MoneyModule.ReadAccount:output_type -> money_module.WalletDetailsResponse
	12, // 48: money_module.MoneyModule.UpdateAccount:output_type -> money_module.WalletDetailsResponse
	12, // 49: money_module.MoneyModule.ArchiveAccount:output_type -> money_module.WalletDetailsResponse
	12, // 50: money_module.MoneyModule.CreateBudget:output_type -> money_module.WalletDetailsResponse
	12, // 51: money_module.MoneyModule.ReadBudget:output_type -> money_module.WalletDetailsResponse
	12, // 52: money_module.MoneyModule.UpdateBudget:output_type -> money_module.WalletDetailsResponse
	12, // 53: money_module.MoneyModule.ArchiveBudget:output_type -> money_module.WalletDetailsResponse
	6,  // 54: money_module.MoneyModule.PayAccountFromBudget:output_type -> money_module.PaymentResponse
	6,  // 55: money_module.MoneyModule.PayBudgetFromAccount:output_type -> money_module.PaymentResponse
	6,  // 56: money_module.MoneyModule.PayRootFromAccount:output_type -> money_module.PaymentResponse
	6,  // 57: money_module.MoneyModule.PayAccountFromRoot:output_type -> money_module.PaymentResponse
	8,  // 58: money_module.MoneyModule.SendBetweenBudgets:output_type -> money_module.SendResponse
	11, // 59: money_module.MoneyModule.GetAccountTransfers:output_type -> money_module.TransfersResponse
	11, // 60: money_module.MoneyModule.GetBudgetTransfers:output_type -> money_module.TransfersResponse
	11, // 61: money_module.MoneyModule.GetSocietyTransfers:output_type -> money_module.TransfersResponse
	46, // [46:62] is the sub-list for method output_type
	30, // [30:46] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_mm_proto_init() }
func file_mm_proto_init() {
	if File_mm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mm_proto_rawDesc), len(file_mm_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mm_proto_goTypes,
		DependencyIndexes: file_mm_proto_depIdxs,
		EnumInfos:         file_mm_proto_enumTypes,
		MessageInfos:      file_mm_proto_msgTypes,
	}.Build()
	File_mm_proto = out.File
	file_mm_proto_goTypes = nil
	file_mm_proto_depIdxs = nil
}
