// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: mm.proto

package money_module_protobuff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MoneyModule_CreateAccount_FullMethodName        = "/money_module.MoneyModule/CreateAccount"
	MoneyModule_ReadAccount_FullMethodName          = "/money_module.MoneyModule/ReadAccount"
	MoneyModule_UpdateAccount_FullMethodName        = "/money_module.MoneyModule/UpdateAccount"
	MoneyModule_ArchiveAccount_FullMethodName       = "/money_module.MoneyModule/ArchiveAccount"
	MoneyModule_CreateBudget_FullMethodName         = "/money_module.MoneyModule/CreateBudget"
	MoneyModule_ReadBudget_FullMethodName           = "/money_module.MoneyModule/ReadBudget"
	MoneyModule_UpdateBudget_FullMethodName         = "/money_module.MoneyModule/UpdateBudget"
	MoneyModule_ArchiveBudget_FullMethodName        = "/money_module.MoneyModule/ArchiveBudget"
	MoneyModule_PayAccountFromBudget_FullMethodName = "/money_module.MoneyModule/PayAccountFromBudget"
	MoneyModule_PayBudgetFromAccount_FullMethodName = "/money_module.MoneyModule/PayBudgetFromAccount"
	MoneyModule_PayRootFromAccount_FullMethodName   = "/money_module.MoneyModule/PayRootFromAccount"
	MoneyModule_PayAccountFromRoot_FullMethodName   = "/money_module.MoneyModule/PayAccountFromRoot"
	MoneyModule_SendBetweenBudgets_FullMethodName   = "/money_module.MoneyModule/SendBetweenBudgets"
	MoneyModule_GetAccountTransfers_FullMethodName  = "/money_module.MoneyModule/GetAccountTransfers"
	MoneyModule_GetBudgetTransfers_FullMethodName   = "/money_module.MoneyModule/GetBudgetTransfers"
	MoneyModule_GetSocietyTransfers_FullMethodName  = "/money_module.MoneyModule/GetSocietyTransfers"
)

// MoneyModuleClient is the client API for MoneyModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoneyModuleClient interface {
	// Metadata only routes
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error)
	ReadAccount(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error)
	ArchiveAccount(ctx context.Context, in *ArchiveWalletRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error)
	CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error)
	ReadBudget(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error)
	UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error)
	ArchiveBudget(ctx context.Context, in *ArchiveWalletRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error)
	// Money routes
	PayAccountFromBudget(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	PayBudgetFromAccount(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	PayRootFromAccount(ctx context.Context, in *RootPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	PayAccountFromRoot(ctx context.Context, in *RootPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	SendBetweenBudgets(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	GetAccountTransfers(ctx context.Context, in *TransfersRequest, opts ...grpc.CallOption) (*TransfersResponse, error)
	GetBudgetTransfers(ctx context.Context, in *TransfersRequest, opts ...grpc.CallOption) (*TransfersResponse, error)
	GetSocietyTransfers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TransfersResponse, error)
}

type moneyModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewMoneyModuleClient(cc grpc.ClientConnInterface) MoneyModuleClient {
	return &moneyModuleClient{cc}
}

func (c *moneyModuleClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetailsResponse)
	err := c.cc.Invoke(ctx, MoneyModule_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) ReadAccount(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetailsResponse)
	err := c.cc.Invoke(ctx, MoneyModule_ReadAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetailsResponse)
	err := c.cc.Invoke(ctx, MoneyModule_UpdateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) ArchiveAccount(ctx context.Context, in *ArchiveWalletRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetailsResponse)
	err := c.cc.Invoke(ctx, MoneyModule_ArchiveAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetailsResponse)
	err := c.cc.Invoke(ctx, MoneyModule_CreateBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) ReadBudget(ctx context.Context, in *GetWalletDetailsRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetailsResponse)
	err := c.cc.Invoke(ctx, MoneyModule_ReadBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetailsResponse)
	err := c.cc.Invoke(ctx, MoneyModule_UpdateBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) ArchiveBudget(ctx context.Context, in *ArchiveWalletRequest, opts ...grpc.CallOption) (*WalletDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletDetailsResponse)
	err := c.cc.Invoke(ctx, MoneyModule_ArchiveBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) PayAccountFromBudget(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, MoneyModule_PayAccountFromBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) PayBudgetFromAccount(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, MoneyModule_PayBudgetFromAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) PayRootFromAccount(ctx context.Context, in *RootPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, MoneyModule_PayRootFromAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) PayAccountFromRoot(ctx context.Context, in *RootPaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, MoneyModule_PayAccountFromRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) SendBetweenBudgets(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, MoneyModule_SendBetweenBudgets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) GetAccountTransfers(ctx context.Context, in *TransfersRequest, opts ...grpc.CallOption) (*TransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransfersResponse)
	err := c.cc.Invoke(ctx, MoneyModule_GetAccountTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) GetBudgetTransfers(ctx context.Context, in *TransfersRequest, opts ...grpc.CallOption) (*TransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransfersResponse)
	err := c.cc.Invoke(ctx, MoneyModule_GetBudgetTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyModuleClient) GetSocietyTransfers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransfersResponse)
	err := c.cc.Invoke(ctx, MoneyModule_GetSocietyTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoneyModuleServer is the server API for MoneyModule service.
// All implementations must embed UnimplementedMoneyModuleServer
// for forward compatibility.
type MoneyModuleServer interface {
	// Metadata only routes
	CreateAccount(context.Context, *CreateAccountRequest) (*WalletDetailsResponse, error)
	ReadAccount(context.Context, *GetWalletDetailsRequest) (*WalletDetailsResponse, error)
	UpdateAccount(context.Context, *UpdateAccountRequest) (*WalletDetailsResponse, error)
	ArchiveAccount(context.Context, *ArchiveWalletRequest) (*WalletDetailsResponse, error)
	CreateBudget(context.Context, *CreateBudgetRequest) (*WalletDetailsResponse, error)
	ReadBudget(context.Context, *GetWalletDetailsRequest) (*WalletDetailsResponse, error)
	UpdateBudget(context.Context, *UpdateBudgetRequest) (*WalletDetailsResponse, error)
	ArchiveBudget(context.Context, *ArchiveWalletRequest) (*WalletDetailsResponse, error)
	// Money routes
	PayAccountFromBudget(context.Context, *PaymentRequest) (*PaymentResponse, error)
	PayBudgetFromAccount(context.Context, *PaymentRequest) (*PaymentResponse, error)
	PayRootFromAccount(context.Context, *RootPaymentRequest) (*PaymentResponse, error)
	PayAccountFromRoot(context.Context, *RootPaymentRequest) (*PaymentResponse, error)
	SendBetweenBudgets(context.Context, *SendRequest) (*SendResponse, error)
	GetAccountTransfers(context.Context, *TransfersRequest) (*TransfersResponse, error)
	GetBudgetTransfers(context.Context, *TransfersRequest) (*TransfersResponse, error)
	GetSocietyTransfers(context.Context, *emptypb.Empty) (*TransfersResponse, error)
	mustEmbedUnimplementedMoneyModuleServer()
}

// UnimplementedMoneyModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoneyModuleServer struct{}

func (UnimplementedMoneyModuleServer) CreateAccount(context.Context, *CreateAccountRequest) (*WalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedMoneyModuleServer) ReadAccount(context.Context, *GetWalletDetailsRequest) (*WalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAccount not implemented")
}
func (UnimplementedMoneyModuleServer) UpdateAccount(context.Context, *UpdateAccountRequest) (*WalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (UnimplementedMoneyModuleServer) ArchiveAccount(context.Context, *ArchiveWalletRequest) (*WalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveAccount not implemented")
}
func (UnimplementedMoneyModuleServer) CreateBudget(context.Context, *CreateBudgetRequest) (*WalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBudget not implemented")
}
func (UnimplementedMoneyModuleServer) ReadBudget(context.Context, *GetWalletDetailsRequest) (*WalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadBudget not implemented")
}
func (UnimplementedMoneyModuleServer) UpdateBudget(context.Context, *UpdateBudgetRequest) (*WalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBudget not implemented")
}
func (UnimplementedMoneyModuleServer) ArchiveBudget(context.Context, *ArchiveWalletRequest) (*WalletDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveBudget not implemented")
}
func (UnimplementedMoneyModuleServer) PayAccountFromBudget(context.Context, *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayAccountFromBudget not implemented")
}
func (UnimplementedMoneyModuleServer) PayBudgetFromAccount(context.Context, *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayBudgetFromAccount not implemented")
}
func (UnimplementedMoneyModuleServer) PayRootFromAccount(context.Context, *RootPaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayRootFromAccount not implemented")
}
func (UnimplementedMoneyModuleServer) PayAccountFromRoot(context.Context, *RootPaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayAccountFromRoot not implemented")
}
func (UnimplementedMoneyModuleServer) SendBetweenBudgets(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBetweenBudgets not implemented")
}
func (UnimplementedMoneyModuleServer) GetAccountTransfers(context.Context, *TransfersRequest) (*TransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountTransfers not implemented")
}
func (UnimplementedMoneyModuleServer) GetBudgetTransfers(context.Context, *TransfersRequest) (*TransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBudgetTransfers not implemented")
}
func (UnimplementedMoneyModuleServer) GetSocietyTransfers(context.Context, *emptypb.Empty) (*TransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSocietyTransfers not implemented")
}
func (UnimplementedMoneyModuleServer) mustEmbedUnimplementedMoneyModuleServer() {}
func (UnimplementedMoneyModuleServer) testEmbeddedByValue()                     {}

// UnsafeMoneyModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoneyModuleServer will
// result in compilation errors.
type UnsafeMoneyModuleServer interface {
	mustEmbedUnimplementedMoneyModuleServer()
}

func RegisterMoneyModuleServer(s grpc.ServiceRegistrar, srv MoneyModuleServer) {
	// If the following call panics, it indicates UnimplementedMoneyModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoneyModule_ServiceDesc, srv)
}

func _MoneyModule_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_ReadAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).ReadAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_ReadAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).ReadAccount(ctx, req.(*GetWalletDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_UpdateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_ArchiveAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).ArchiveAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_ArchiveAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).ArchiveAccount(ctx, req.(*ArchiveWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_CreateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).CreateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_CreateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).CreateBudget(ctx, req.(*CreateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_ReadBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).ReadBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_ReadBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).ReadBudget(ctx, req.(*GetWalletDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_UpdateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).UpdateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_UpdateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).UpdateBudget(ctx, req.(*UpdateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_ArchiveBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).ArchiveBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_ArchiveBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).ArchiveBudget(ctx, req.(*ArchiveWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_PayAccountFromBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).PayAccountFromBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_PayAccountFromBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).PayAccountFromBudget(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_PayBudgetFromAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).PayBudgetFromAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_PayBudgetFromAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).PayBudgetFromAccount(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_PayRootFromAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).PayRootFromAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_PayRootFromAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).PayRootFromAccount(ctx, req.(*RootPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_PayAccountFromRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).PayAccountFromRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_PayAccountFromRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).PayAccountFromRoot(ctx, req.(*RootPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_SendBetweenBudgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).SendBetweenBudgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_SendBetweenBudgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).SendBetweenBudgets(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_GetAccountTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).GetAccountTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_GetAccountTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).GetAccountTransfers(ctx, req.(*TransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_GetBudgetTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).GetBudgetTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_GetBudgetTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).GetBudgetTransfers(ctx, req.(*TransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyModule_GetSocietyTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyModuleServer).GetSocietyTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyModule_GetSocietyTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyModuleServer).GetSocietyTransfers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MoneyModule_ServiceDesc is the grpc.ServiceDesc for MoneyModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoneyModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "money_module.MoneyModule",
	HandlerType: (*MoneyModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _MoneyModule_CreateAccount_Handler,
		},
		{
			MethodName: "ReadAccount",
			Handler:    _MoneyModule_ReadAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _MoneyModule_UpdateAccount_Handler,
		},
		{
			MethodName: "ArchiveAccount",
			Handler:    _MoneyModule_ArchiveAccount_Handler,
		},
		{
			MethodName: "CreateBudget",
			Handler:    _MoneyModule_CreateBudget_Handler,
		},
		{
			MethodName: "ReadBudget",
			Handler:    _MoneyModule_ReadBudget_Handler,
		},
		{
			MethodName: "UpdateBudget",
			Handler:    _MoneyModule_UpdateBudget_Handler,
		},
		{
			MethodName: "ArchiveBudget",
			Handler:    _MoneyModule_ArchiveBudget_Handler,
		},
		{
			MethodName: "PayAccountFromBudget",
			Handler:    _MoneyModule_PayAccountFromBudget_Handler,
		},
		{
			MethodName: "PayBudgetFromAccount",
			Handler:    _MoneyModule_PayBudgetFromAccount_Handler,
		},
		{
			MethodName: "PayRootFromAccount",
			Handler:    _MoneyModule_PayRootFromAccount_Handler,
		},
		{
			MethodName: "PayAccountFromRoot",
			Handler:    _MoneyModule_PayAccountFromRoot_Handler,
		},
		{
			MethodName: "SendBetweenBudgets",
			Handler:    _MoneyModule_SendBetweenBudgets_Handler,
		},
		{
			MethodName: "GetAccountTransfers",
			Handler:    _MoneyModule_GetAccountTransfers_Handler,
		},
		{
			MethodName: "GetBudgetTransfers",
			Handler:    _MoneyModule_GetBudgetTransfers_Handler,
		},
		{
			MethodName: "GetSocietyTransfers",
			Handler:    _MoneyModule_GetSocietyTransfers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mm.proto",
}
